apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-oms
  template:
    metadata:
      labels:
        app: ecommerce-oms
    spec:
      containers:
        - name: ecommerce-oms
          image: YOUR_DOCKERHUB_USERNAME/ecommerce-oms:1.0.0
          imagePullPolicy: IfNotPresent